//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2._2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.comments = new HashSet<comments>();
            this.favoritevideo = new HashSet<favoritevideo>();
            this.favoriteplaylist = new HashSet<favoriteplaylist>();
            this.favoritesong = new HashSet<favoritesong>();
            this.playlist = new HashSet<playlist>();
            this.songlike = new HashSet<songlike>();
            this.userreport = new HashSet<userreport>();
            this.videolike = new HashSet<videolike>();
        }
    
        public int id { get; set; }
        public string Accountname { get; set; }
        public string password { get; set; }
        public int accounttypeid { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string avatar { get; set; }
        public string moreinfo { get; set; }
        public string notes { get; set; }
        public bool Isactive { get; set; }
        public System.DateTime lastloggedin { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
    
        public virtual accounttype accounttype { get; set; }
        public virtual ICollection<comments> comments { get; set; }
        public virtual ICollection<favoritevideo> favoritevideo { get; set; }
        public virtual ICollection<favoriteplaylist> favoriteplaylist { get; set; }
        public virtual ICollection<favoritesong> favoritesong { get; set; }
        public virtual ICollection<playlist> playlist { get; set; }
        public virtual ICollection<songlike> songlike { get; set; }
        public virtual ICollection<userreport> userreport { get; set; }
        public virtual ICollection<videolike> videolike { get; set; }
        public virtual bannedreason bannedreason { get; set; }
    }
}
