//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2._2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bannedreason
    {
        public bannedreason()
        {
            this.Account = new HashSet<Account>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string descriptions { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
    }
}
