//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2._2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class bannedreason
    {
        public bannedreason()
        {
            this.bannedaccount = new HashSet<bannedaccount>();
        }
        
        [Display(Name="Mã")]
        public int id { get; set; }

        [Required(ErrorMessage="Tiêu đề không được bỏ trống")]
        [Display(Name="Tiêu đề")]
        public string title { get; set; }

        [Display(Name="Mô tả")]
        public string descriptions { get; set; }
    
        public virtual ICollection<bannedaccount> bannedaccount { get; set; }
    }
}
