//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2._2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public comments()
        {
            this.playlistcomments = new HashSet<playlistcomments>();
            this.songcomments = new HashSet<songcomments>();
            this.videocomments = new HashSet<videocomments>();
        }
    
        public int id { get; set; }
        public int accountid { get; set; }
        public string contents { get; set; }
        public System.DateTime datecreated { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<playlistcomments> playlistcomments { get; set; }
        public virtual ICollection<songcomments> songcomments { get; set; }
        public virtual ICollection<videocomments> videocomments { get; set; }
    }
}
