//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2._2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menuItem
    {
        public menuItem()
        {
            this.menuItem1 = new HashSet<menuItem>();
        }
    
        public int id { get; set; }
        public int menuContainerID { get; set; }
        public Nullable<int> menuParentID { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
    
        public virtual menuContainer menuContainer { get; set; }
        public virtual ICollection<menuItem> menuItem1 { get; set; }
        public virtual menuItem menuItem2 { get; set; }
    }
}
