//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2._2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        public song()
        {
            this.favoritesong = new HashSet<favoritesong>();
            this.playlistitem = new HashSet<playlistitem>();
            this.songcategory = new HashSet<songcategory>();
            this.songcomments = new HashSet<songcomments>();
            this.songlike = new HashSet<songlike>();
            this.songmusician = new HashSet<songmusician>();
            this.songsinger = new HashSet<songsinger>();
            this.userreportSong = new HashSet<userreportSong>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string fileSrc { get; set; }
        public int accountid { get; set; }
        public int duration { get; set; }
        public int views { get; set; }
        public string moreinfo { get; set; }
        public string lyricfile { get; set; }
        public string lyric { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<favoritesong> favoritesong { get; set; }
        public virtual ICollection<playlistitem> playlistitem { get; set; }
        public virtual ICollection<songcategory> songcategory { get; set; }
        public virtual ICollection<songcomments> songcomments { get; set; }
        public virtual ICollection<songlike> songlike { get; set; }
        public virtual ICollection<songmusician> songmusician { get; set; }
        public virtual ICollection<songsinger> songsinger { get; set; }
        public virtual ICollection<userreportSong> userreportSong { get; set; }
    }
}
