//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2._2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userreport
    {
        public int id { get; set; }
        public int accountid { get; set; }
        public int relatedvideoid { get; set; }
        public int relatedsongid { get; set; }
        public int relatedaccountid { get; set; }
        public string moreinfo { get; set; }
        public Nullable<System.DateTime> Dateadded { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual song song { get; set; }
        public virtual video video { get; set; }
    }
}
