//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2._2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public video()
        {
            this.favoritevideo = new HashSet<favoritevideo>();
            this.userreportVideo = new HashSet<userreportVideo>();
            this.videocategory = new HashSet<videocategory>();
            this.videocomments = new HashSet<videocomments>();
            this.videolike = new HashSet<videolike>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public int duration { get; set; }
        public int views { get; set; }
        public string thumbnail { get; set; }
        public string moreinfo { get; set; }
        public System.DateTime datecreated { get; set; }
    
        public virtual ICollection<favoritevideo> favoritevideo { get; set; }
        public virtual ICollection<userreportVideo> userreportVideo { get; set; }
        public virtual ICollection<videocategory> videocategory { get; set; }
        public virtual ICollection<videocomments> videocomments { get; set; }
        public virtual ICollection<videolike> videolike { get; set; }
    }
}
