//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_2._2_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class videocategory
    {
        public int id { get; set; }
        public int videoid { get; set; }
        public int categoryid { get; set; }
    
        public virtual category category { get; set; }
        public virtual video video { get; set; }
    }
}
